spring:
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/pybbs?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: cly2017123$qweR
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
banner:
  location: banner.txt
site:
  name: 有朋自对面来
  baseUrl: http://www.biubiuq.cn/
  baseUrlC: http://www.biubiuq.cn
  beianName: 沪ICP备17011016号
  sessionName: _user
  adminSessionName: _admin_user
  cookieName: _token
  adminCookieName: _admin_token
  cookieDomain: www.biubiuq.cn
  cookieExpireTime: 30 # 单位天
  pageSize: 20
  avatarPath: /Users/tomoya/git/github/pybbs/src/main/resources/static/images/avatar/
  uploadPath: /Users/tomoya/git/github/pybbs/src/main/resources/static/images/upload/
  sections:
    - 分享
    - 问答
    - 社会
    - 水区
  theme: bootstrap