spring:
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/pybbs?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
banner:
  location: banner.txt
site:
  name: 有朋自对面来
  baseUrl: http://localhost:8080/
  sessionName: _user
  adminSessionName: _admin_user
  cookieName: _token
  adminCookieName: _admin_token
  cookieDomain: localhost
  cookieExpireTime: 30 # 单位天
  pageSize: 20
  avatarPath: C:/tmp/pybbs/
  uploadPath: C:/tmp/pybbs/
  sections:
    - 分享
    - 问答
    - 新闻
    - 水区
  theme: bootstrap